// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjbosC5gbX5dzn_1d0s2t1P5zNH8PJ1LE',
    appId: '1:904559981404:web:2543f3b14631f602510799',
    messagingSenderId: '904559981404',
    projectId: 'kopifood-4859d',
    authDomain: 'kopifood-4859d.firebaseapp.com',
    storageBucket: 'kopifood-4859d.appspot.com',
    measurementId: 'G-6HB4FHPM6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSbsWydRpVuA14lV7FdIMNqMDYo8KvzCg',
    appId: '1:904559981404:android:797a63f05673bd50510799',
    messagingSenderId: '904559981404',
    projectId: 'kopifood-4859d',
    storageBucket: 'kopifood-4859d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmDHAzvNMrd9YLnpWpvUv08VhZCevoyjo',
    appId: '1:904559981404:ios:351dbfcd65740901510799',
    messagingSenderId: '904559981404',
    projectId: 'kopifood-4859d',
    storageBucket: 'kopifood-4859d.appspot.com',
    iosClientId:
        '904559981404-c64pkd68jo6jkb6dr36p9b6ffcbih4pi.apps.googleusercontent.com',
    iosBundleId: 'com.example.kopifood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmDHAzvNMrd9YLnpWpvUv08VhZCevoyjo',
    appId: '1:904559981404:ios:351dbfcd65740901510799',
    messagingSenderId: '904559981404',
    projectId: 'kopifood-4859d',
    storageBucket: 'kopifood-4859d.appspot.com',
    iosClientId:
        '904559981404-c64pkd68jo6jkb6dr36p9b6ffcbih4pi.apps.googleusercontent.com',
    iosBundleId: 'com.example.kopifood',
  );
}
